accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),

    path('check-auth/', views.check_auth, name='check_auth'),

]

booking/urls.py
from django.urls import path
from booking import views

app_name='booking'

urlpatterns = [
   
    ]

restaurant_app/urls.py
from django.urls import path
from restaurant_app import views

app_name='restaurant_app'

urlpatterns = [
    path('test/',views.test,name='test'),
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('services/',views.service,name='services'),
    path('menu/<str:category>/',views.menu,name='menu'),
    path('m/<str:category>/',views.menu_new,name='menu_new'),
    path('contact/',views.contact,name='contact'),

    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('order/', views.cart, name='cart'),
    path('update_cart_item/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('remove_cart_item/<int:item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('dashboard/', views.dashboard, name='dashboard'),
    
 
    # Drinks
    path('add-drink/', views.add_drink, name='add_drinks'),
    path('edit-drink/<int:drink_id>/', views.edit_drink, name='edit_drink'),
    path('delete-drink/<int:drink_id>/', views.delete_drink, name='delete_drink'),

    # Salads
    path('add-salad/', views.add_salad, name='add_salads'),
    path('edit-salad/<int:salad_id>/', views.edit_salad, name='edit_salad'),
    path('delete-salad/<int:salad_id>/', views.delete_salad, name='delete_salad'),

    # Meals
    path('add-meal/', views.add_meal, name='add_meals'),
    path('edit-meal/<int:meal_id>/', views.edit_meal, name='edit_meal'),
    path('delete-meal/<int:meal_id>/', views.delete_meal, name='delete_meal'),

    # Sandwiches
    path('add-sandwich/', views.add_sandwich, name='add_sandwiches'),
    path('edit-sandwich/<int:sandwich_id>/', views.edit_sandwich, name='edit_sandwiche'),
    path('delete-sandwich/<int:sandwich_id>/', views.delete_sandwich, name='delete_sandwiche'),

    # Grills
    path('add-grill/', views.add_grill, name='add_grills'),
    path('edit-grill/<int:grill_id>/', views.edit_grill, name='edit_grill'),
    path('delete-grill/<int:grill_id>/', views.delete_grill, name='delete_grill'),

    # Sweets
    path('add-sweet/', views.add_sweet, name='add_sweets'),
    path('edit-sweet/<int:sweet_id>/', views.edit_sweet, name='edit_sweet'),
    path('delete-sweet/<int:sweet_id>/', views.delete_sweet, name='delete_sweet'),

    path('add-chef/',views.add_chef,name='add_chef'),
    path('edit-chef/<int:chef_id>/',views.edit_chef,name='edit_chef'),
    path('delete-chef/<int:chef_id>/',views.delete_chef,name='delete_chef'),

    path('add-comment/',views.add_comment,name='add_comment'),
    path('delete-comment/<int:comment_id>/',views.delete_comment,name='delete_comment'),
    path('approve-comment/<int:comment_id>/', views.update_comment_status, {'status': 'approved'}, name='approve_comment'),
    path('reject-comment/<int:comment_id>/', views.update_comment_status, {'status': 'rejected'}, name='reject_comment'),

    path('edit-contact/<int:contact_id>/',views.edit_contact,name='edit_contact'),
    path('edit-rest-detail/', views.edit_rest_detail, name='edit_rest_detail'),

    path('create-payment/', views.create_payment, name='create_payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/cancel/', views.payment_cancel, name='payment_cancel'),

    path('view_order/<int:order_id>/', views.view_order, name='view_order'),
    path('delete_order/<int:order_id>/', views.delete_order, name='delete_order'),
    path('get-cart-item-count/', views.get_cart_item_count, name='get_cart_item_count'),
    

    path('services/add/', views.add_service, name='add_service'),
    path('services/edit/<int:service_id>/', views.edit_service, name='edit_service'),
    path('services/delete/<int:service_id>/', views.delete_service, name='delete_service'),

]

restaurant_project/urls.py
from django.contrib import admin
from django.urls import path,include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('restaurant_app.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('accounts/',include('accounts.urls')),
    # path('stars/restaurant/booking/',include('booking.urls')),

    # path('auth/', include('social_django.urls', namespace='social')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#test

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Account(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, related_name='account')
    job_title = models.CharField(max_length=255, blank=True, default='Client')
    image = models.ImageField(upload_to='clients/', default='defa/client.png')  # Add profile image
    credits = models.SmallIntegerField(default=0)    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        
        # Resize the image
        if self.image:
            img_path = self.image.path
            with Image.open(img_path) as img:
                    output_size = (50, 50)
                    img = img.resize(output_size, Image.Resampling.LANCZOS)
                    img.save(img_path)

    def __str__(self):
        return f'{self.user.username} account'
    
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 =forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2= forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control','placeholder': 'Enter your email'}))

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Add styling to all fields
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'username':
                field.widget.attrs['placeholder'] = 'Choose a username'
            elif 'password' in field_name:
                field.widget.attrs['placeholder'] = 'Enter your password'

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

    

class CustomAuthenticationForm(AuthenticationForm):
        username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'Enter your username'}))
        password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder': 'Enter your password'}))

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from .forms import UserRegistrationForm,CustomAuthenticationForm
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from restaurant_app.models import Rest_detail

class RegisterView(CreateView):
    form_class = UserRegistrationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('accounts:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rest_detail'] = Rest_detail.objects.first()  # Get the first object
        return context



class CustomLoginView(LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('restaurant_app:home')
    # redirect_authenticated_user = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rest_detail'] = Rest_detail.objects.first()  # Get the first object
        return context




def check_auth(request):
    return JsonResponse({'authenticated': request.user.is_authenticated})

accounts/templates/accounts/base_login.html
{% load static %}

<head>
    <meta charset="utf-8">
    <title>Star Restaurant</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    
    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="https://unpkg.com/htmx.org"></script>

</head>
{% include "accounts/navbar_login.html" %}

<!-- Page Header-->

<!-- Main Content-->

{% block content %}
{% endblock content %}


<!-- Footer-->
{% include "restaurant/footer.html" %}

<!-- JavaScript Libraries -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/easing.min.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/counterup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/moment-timezone.min.js' %}"></script>
<script src="{% static 'js/tempusdominus-bootstrap-4.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

accounts/templates/accounts/footer.html
<!-- Footer Start -->
<div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Company</h4>
                <a class="btn btn-link" href="{% url 'restaurant_app:about'%}">About Us</a>
                <a class="btn btn-link" href="{% url 'restaurant_app:contact'%}">Contact Us</a>
                <a class="btn btn-link" href="">Reservation</a>
                <a class="btn btn-link" href="">Privacy Policy</a>
                <a class="btn btn-link" href="">Terms & Condition</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Contact</h4>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Opening</h4>
                <h5 class="text-light fw-normal">Monday - Saturday</h5>
                <p>09AM - 09PM</p>
                <h5 class="text-light fw-normal">Sunday</h5>
                <p>10AM - 08PM</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Star Restaurant</h4> 
                <h5 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>Stars Restoran</h5>

                {% comment %} <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                <a href="{% url  'accounts:register' %}"> <div class="position-relative mx-auto" style="max-width: 400px;">
                    
                    <input class="form-control border-primary w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                    <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                </div></a> {% endcomment %}
                <img src="{{ rest_detail.image.url }}" alt="Logo" style="width: 200px; height: 180px; object-fit: cover; margin-right: 10px;">

            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved. 
                    
                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a href="{% url 'restaurant_app:home'%}">Home</a>
                        <a href="">Cookies</a>
                        <a href="">Help</a>
                        <a href="">FQAs</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

accounts/templates/accounts/login.html
<!-- accounts/login.html -->
{% extends 'accounts/base_login.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">Login</h2>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.username.label_tag }}
                    {{ form.username }}
                </div>
                <div class="mb-3">
                    {{ form.password.label_tag }}
                    {{ form.password }}
                </div>
                <button type="submit" class="btn btn-primary w-100">Login</button>
            </form>
            <div class="text-center mt-3">
                <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-danger w-100 d-flex align-items-center justify-content-center">
                    <i class="fab fa-google me-2"></i> Login with Google
                </a>
                            </div>
            <p class="mt-3 text-center">Don't have an account? <a href="{% url 'accounts:register' %}">Register</a></p>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/navbar_login.html
{%load static%}
 <!-- navbar .html -->
 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Navbar</title>
     <!-- Bootstrap CSS -->
     <!-- Font Awesome CSS -->
 </head>
 <body>
  <!-- Navbar & Hero Start -->
  <div class="container-xxl position-relative p-0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
        <a href="" class="navbar-brand p-0 d-flex align-items-center">
            <!-- Logo -->
            <img src="{{ rest_detail.image.url }}" alt="Logo" class="img-fluid" style="max-height: 80px;">                <!-- Restaurant Name -->
            <h1 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>Star Restoran</h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="fa fa-bars"></span>
        </button>



        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0 pe-4">
                <a href="{% url 'restaurant_app:home' %}" class="nav-item nav-link ">Home</a>
                <a href="{% url 'restaurant_app:about' %}" class="nav-item nav-link">About</a>
                <a href="{% url 'restaurant_app:services' %}" class="nav-item nav-link">Service</a>
                <a href="{% url 'restaurant_app:menu' category='food_menu' %}" class="nav-item nav-link {{ menu|default:'' }}">Menu</a>
                <a href="{% url 'restaurant_app:contact' %}" class="nav-item nav-link {{ contact|default:'' }}">Contact</a>
                {% if request.user.is_staff %}
                <a href="{% url 'restaurant_app:dashboard' %}" class="nav-item nav-link {{ Dashboard|default:'' }}">Admin Dashboard</a>
                {% endif %}
            </div>
        
            <!-- Wrap the cart and logout/login buttons in a flex container -->
            <div class="d-flex align-items-center gap-3">
                <!-- Cart Icon -->
                <a href="{% url 'restaurant_app:cart' %}" class="btn btn-primary py-2 px-4 position-relative">
                    <i class="fas fa-shopping-cart"></i>
                    <span id="cartItemCount" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                        {{ request.user.cart.cart_items.count|default:0 }}
                    </span>
                </a>
        
                <!-- Logout/Login Button -->
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'accounts:logout' %}" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger d-flex align-items-center py-2 px-4">
                        <i class="fas fa-sign-out-alt me-2"></i> Logout
                    </button>
                </form>
                {% else %}
                <a href="{% url 'accounts:login' %}" class="btn btn-primary d-flex align-items-center py-2 px-4">
                    <i class="fas fa-sign-in-alt me-2"></i> Login
                </a>
                {% endif %}
            </div>
        </div>
        
        </div>




    </nav>
    <div class="container-xxl py-5 bg-dark hero-header mb-5">
        <div class="container text-center my-5 pt-5 pb-4">
            <!-- Dynamic Page Title -->
            <h1 class="display-3 text-white mb-3 animated slideInDown">Welcome Login Here!</h1>
    
            <!-- Dynamic Breadcrumb -->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="{%url 'restaurant_app:home'%}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{%url 'restaurant_app:about'%}">About</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">LOGIN</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- Navbar & Hero End -->
 <!-- Bootstrap JS Bundle -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

accounts/templates/accounts/register.html
<!-- accounts/register.html -->
{% extends 'accounts/base_login.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">Register</h2>
            <form method="post">
                {% csrf_token %}
                
                <!-- Username Field -->
                <div class="mb-3">
                    {{ form.username.label_tag }}
                    {{ form.username }}
                    {% if form.username.errors %}
                        <div class="text-danger">
                            {% for error in form.username.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <!-- Email Field -->
                <div class="mb-3">
                    {{ form.email.label_tag }}
                    {{ form.email }}
                    {% if form.email.errors %}
                        <div class="text-danger">
                            {% for error in form.email.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <!-- Password Field -->
                <div class="mb-3">
                    <label for="{{ form.password1.id_for_label }}">Password</label>
                    {{ form.password1 }}
                    {% if form.password1.errors %}
                        <div class="text-danger">
                            {% for error in form.password1.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <!-- Confirm Password Field -->
                <div class="mb-3">
                    <label for="{{ form.password2.id_for_label }}">Confirm Password</label>
                    {{ form.password2 }}
                    {% if form.password2.errors %}
                        <div class="text-danger">
                            {% for error in form.password2.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <!-- Register Button -->
                <button type="submit" class="btn btn-success w-100">Register</button>
            </form>

            <!-- Google Registration Button -->
            <a href="{% url 'social:begin' 'google-oauth2' %}" class="google-login-button btn btn-outline-dark w-100 d-flex align-items-center justify-content-center mt-3">
                <i class="fab fa-google me-2 text-danger"></i> Register with Google
            </a>

            <!-- Login Link -->
            <p class="mt-3 text-center">Already have an account? <a href="{% url 'accounts:login' %}">Login</a></p>
        </div>
    </div>
</div>
{% endblock %}