accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('accounts:login')), name='logout'),

    path('check-auth/', views.check_auth, name='check_auth'),

]

booking/urls.py
from django.urls import path
from booking import views

app_name='booking'

urlpatterns = [
   
    ]

restaurant_app/urls.py
from django.urls import path
from restaurant_app import views

app_name='restaurant_app'

urlpatterns = [
    path('test/',views.test,name='test'),
    path('',views.home,name='home'),
    path('about/',views.about,name='about'),
    path('services/',views.service,name='services'),
    path('menu/<str:category>/',views.menu,name='menu'),
    path('m/<str:category>/',views.menu_new,name='menu_new'),
    path('contact/',views.contact,name='contact'),

    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('order/', views.cart, name='cart'),
    path('update_cart_item/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('remove_cart_item/<int:item_id>/', views.remove_cart_item, name='remove_cart_item'),

    path('dashboard/', views.dashboard, name='dashboard'),
    
 
    # Drinks
    path('add-drink/', views.add_drink, name='add_drinks'),
    path('edit-drink/<int:drink_id>/', views.edit_drink, name='edit_drink'),
    path('delete-drink/<int:drink_id>/', views.delete_drink, name='delete_drink'),

    # Salads
    path('add-salad/', views.add_salad, name='add_salads'),
    path('edit-salad/<int:salad_id>/', views.edit_salad, name='edit_salad'),
    path('delete-salad/<int:salad_id>/', views.delete_salad, name='delete_salad'),

    # Meals
    path('add-meal/', views.add_meal, name='add_meals'),
    path('edit-meal/<int:meal_id>/', views.edit_meal, name='edit_meal'),
    path('delete-meal/<int:meal_id>/', views.delete_meal, name='delete_meal'),

    # Sandwiches
    path('add-sandwich/', views.add_sandwich, name='add_sandwiches'),
    path('edit-sandwich/<int:sandwich_id>/', views.edit_sandwich, name='edit_sandwiche'),
    path('delete-sandwich/<int:sandwich_id>/', views.delete_sandwich, name='delete_sandwiche'),

    # Grills
    path('add-grill/', views.add_grill, name='add_grills'),
    path('edit-grill/<int:grill_id>/', views.edit_grill, name='edit_grill'),
    path('delete-grill/<int:grill_id>/', views.delete_grill, name='delete_grill'),

    # Sweets
    path('add-sweet/', views.add_sweet, name='add_sweets'),
    path('edit-sweet/<int:sweet_id>/', views.edit_sweet, name='edit_sweet'),
    path('delete-sweet/<int:sweet_id>/', views.delete_sweet, name='delete_sweet'),

    path('add-chef/',views.add_chef,name='add_chef'),
    path('edit-chef/<int:chef_id>/',views.edit_chef,name='edit_chef'),
    path('delete-chef/<int:chef_id>/',views.delete_chef,name='delete_chef'),

    path('add-comment/',views.add_comment,name='add_comment'),
    path('delete-comment/<int:comment_id>/',views.delete_comment,name='delete_comment'),
    path('approve-comment/<int:comment_id>/', views.update_comment_status, {'status': 'approved'}, name='approve_comment'),
    path('reject-comment/<int:comment_id>/', views.update_comment_status, {'status': 'rejected'}, name='reject_comment'),

    path('edit-contact/<int:contact_id>/',views.edit_contact,name='edit_contact'),
    path('edit-rest-detail/', views.edit_rest_detail, name='edit_rest_detail'),

    path('create-payment/', views.create_payment, name='create_payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/cancel/', views.payment_cancel, name='payment_cancel'),

    path('view_order/<int:order_id>/', views.view_order, name='view_order'),
    path('delete_order/<int:order_id>/', views.delete_order, name='delete_order'),
    path('get-cart-item-count/', views.get_cart_item_count, name='get_cart_item_count'),
    

    path('services/add/', views.add_service, name='add_service'),
    path('services/edit/<int:service_id>/', views.edit_service, name='edit_service'),
    path('services/delete/<int:service_id>/', views.delete_service, name='delete_service'),

]

restaurant_project/urls.py
from django.contrib import admin
from django.urls import path,include


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('restaurant_app.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('accounts/',include('accounts.urls')),
    # path('stars/restaurant/booking/',include('booking.urls')),

    # path('auth/', include('social_django.urls', namespace='social')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#test

restaurant_app/views.py
from django.shortcuts import render
from .models import AboutUs, AboutUsImage, Rest_detail,Services,Drinks,Meals,Sandwiches,Grills,Sweets,Salads,Chefs,Contact,Cart,CartItem,Comment
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from django.db.models import QuerySet
import random
from django.urls import reverse
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from .forms import ContactForm, ServiceForm
from django.contrib import messages
from itertools import chain
from random import shuffle
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from .forms import DrinkForm, SaladForm, MealForm, SandwichForm, GrillForm, SweetForm,ChefForm,CommentForm,ContactUsForm,RestDetailForm,UserInfoForm
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.views.generic import DeleteView
from django.urls import reverse_lazy

#                                       <<<<<<     test    >>>>>
def test(request):
    services = Services.objects.all()
    return render(request, 'restaurant/navbar_other.html',{'services':services})





#                                       <<<<<<     Home    >>>>>

def home(request):
    rest_detail = get_object_or_404(Rest_detail,pk =1)
    services = Services.objects.all()
    about_us = AboutUs.objects.first()
    about_us_images = AboutUsImage.objects.filter(about_us=about_us) if about_us else None
    drinks = Drinks.objects.all()
    meals = Meals.objects.all()
    sandwiches = Sandwiches.objects.all()
    grills = Grills.objects.all()
    sweets = Sweets.objects.all()
    salads = Salads.objects.all()
    # clients = Clients.objects.all()
    comments = Comment.objects.filter(status='approved').order_by('-created_at')

    chefs = Chefs.objects.all()
    if chefs.count()>=4:
        chefs = random.sample(list(chefs), 4)

    combined_items = list(chain(drinks, meals, sandwiches, grills, sweets, salads))
    shuffle(combined_items)  # Shuffle the combined items
    items = combined_items[:10]  # Get 10 random items

    # Ensure there are items before slicing
    if items:
        half = len(items) // 2
        first_half = items[:half]
        second_half = items[half:]
    else:
        first_half = []
        second_half = []

    context = {
        'rest_detail': rest_detail,
        'services': services,
        'about_us': about_us,
        'about_us_images': about_us_images,
        'drinks': drinks,
        'meals': meals,
        'sandwiches': sandwiches,
        'grills': grills,
        'sweets': sweets,
        'salads': salads,
        'chefs': chefs,
        # 'clients': clients,
        'comments':comments,
        'first_half': first_half,
        'second_half': second_half,
        }
    return render(request,'restaurant/index.html',context)


#                                       <<<<<<     About    >>>>>

def about(request):
    about_us = AboutUs.objects.first()
    about_us_images = AboutUsImage.objects.filter(about_us=about_us) if about_us else None
    chefs_list = Chefs.objects.all()
    # paginator = Paginator(chefs_list,8)
    # page_number = request.GET.get('page')
    # chefs  = paginator.get_page(page_number)
    rest_detail = get_object_or_404(Rest_detail,pk =1)
    breadcrumb_section_url = reverse('restaurant_app:services')


    context = {
        'about_us': about_us,
        'about_us_images': about_us_images,
        'page_title': 'About Us',
        'breadcrumb_section': 'Services',
        'breadcrumb_section_url': breadcrumb_section_url,
        'breadcrumb_active': 'About',
        'about':'active',
        'chefs':chefs_list,
        'rest_detail': rest_detail,

        }
    return render(request,'restaurant/about.html',context)





#                                       <<<<<<     Service    >>>>>

def service(request):
    services = Services.objects.all()
    rest_detail = get_object_or_404(Rest_detail,pk =1)
    breadcrumb_section_url = reverse('restaurant_app:about')
    comments = Comment.objects.filter(status='approved').order_by('-created_at')


    context = {
        'services': services,
        'service':'active',
        'page_title': 'Services',
        'breadcrumb_section': 'About',
        'breadcrumb_active': 'Services',
        'rest_detail': rest_detail,
        'breadcrumb_section_url': breadcrumb_section_url,
        'comments': comments,


        }
    return render(request,'restaurant/services.html',context)


@staff_member_required
def add_service(request):
    if request.method == 'POST':
        form = ServiceForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Service added successfully!')  # Success message
            return redirect('restaurant_app:dashboard')  # Redirect to dashboard
        else:
            messages.error(request, 'Failed to add service. Please check the form.')  # Error message
    else:
        form = ServiceForm()
    return render(request, 'restaurant/services/add_service.html', {'form': form})



@staff_member_required
def edit_service(request, service_id):
    service = get_object_or_404(Services, id=service_id)
    if request.method == 'POST':
        form = ServiceForm(request.POST, instance=service)
        if form.is_valid():
            form.save()
            messages.success(request, 'Service updated successfully!')  # Success message
            return redirect('restaurant_app:dashboard')  # Redirect to services list
        else:
            messages.error(request, 'Failed to update service. Please check the form.')  # Error message
    else:
        form = ServiceForm(instance=service)
    return render(request, 'restaurant/services/edit_service.html', {'form': form, 'service': service})



@staff_member_required
def delete_service(request, service_id):
    service = get_object_or_404(Services, id=service_id)
    service.delete()
    messages.success(request, "Service deleted successfully!")
    return redirect('restaurant_app:dashboard')
#                                       <<<<<<     Menu    >>>>>

def menu(request, category):

    drinks = Drinks.objects.all().order_by('-price')
    meals = Meals.objects.all().order_by('-price')
    sandwiches = Sandwiches.objects.all().order_by('-price')
    grills = Grills.objects.all().order_by('-price')
    sweets = Sweets.objects.all().order_by('-price')
    salads = Salads.objects.all().order_by('-price')
    rest_detail = get_object_or_404(Rest_detail,pk =1)
    breadcrumb_section_url = reverse('restaurant_app:cart')

        # Filter menu items based on the selected category
    if category == 'Drinks':
        items = drinks
        name_page = 'Drinks'
    elif category == 'Meals':
        items = meals
        name_page = 'Meals'
    elif category == 'Sandwiches':
        items = sandwiches
        name_page = 'Sandwiches'
    elif category == 'Grills':
        items = grills
        name_page = 'Grills'
    elif category == 'Sweets':
        items = sweets
        name_page = 'Sweets'
    elif category == 'Salads':
        items = salads
        name_page = 'Salads'
    else:
        # Combine all categories using chain and shuffle the items
        combined_items = list(chain(drinks, meals, sandwiches, grills, sweets, salads))
        shuffle(combined_items)  # Shuffle the combined items
        items = combined_items[:10]  # Get 10 random items
        name_page = 'Most Popular Items'

    # Ensure there are items before slicing
    if items:
        half = len(items) // 2
        first_half = items[:half]
        second_half = items[half:]
    else:
        first_half = []
        second_half = []


    if request.method == 'POST':
        object_id = request.POST.get('object_id')
        # content_type = request.POST.get('content_type')
        size = request.POST.get('size')
        quantity = request.POST.get('quantity')
    else:
        content_type = 'Drinks'
        object_id = 5
    content_type = object_id.__class__
    # food_type = get_object_or_404(content_type,id=object_id)

    
    context = {
        'menu':'active',
        'page_title': 'Food Menu',
        'breadcrumb_section': 'my orders',
        'breadcrumb_active': 'Menu',
        'items': items,
        'category': category,
        'first_half': first_half,
        'second_half': second_half,
        'name_page': name_page,
        'rest_detail':rest_detail,
        'breadcrumb_section_url': breadcrumb_section_url,

        }
    return render(request,'restaurant/menu.html',context)





def menu_new(request, category):
    drinks = Drinks.objects.all().order_by('-price')
    meals = Meals.objects.all().order_by('-price')
    sandwiches = Sandwiches.objects.all().order_by('-price')
    grills = Grills.objects.all().order_by('-price')
    sweets = Sweets.objects.all().order_by('-price')
    salads = Salads.objects.all().order_by('-price')
    rest_detail = get_object_or_404(Rest_detail, pk=1)

    context = {
        'drinks': drinks,
        'meals': meals,
        'sandwiches': sandwiches,
        'grills': grills,
        'sweets': sweets,
        'salads': salads,
        'category': category,
        'rest_detail': rest_detail,
    }
    return render(request, 'restaurant/menu_new.html', context)






#                                       <<<<<<     Testimonial    >>>>>

def testimonial(request):
    # clients = Clients.objects.all()
    rest_detail = get_object_or_404(Rest_detail,pk =1)

    context = {
        # 'clients': clients,
        'rest_detail':rest_detail,
        }
    return render(request,'testimonial.html',context)



#                                       <<<<<<     Team    >>>>>

def our_team(request):
    chefs = Chefs.objects.all()
    rest_detail = get_object_or_404(Rest_detail,pk =1)

restaurant_app/templates/admin_templates/base_admin.html
{% load static %}

<head>
    <meta charset="utf-8">
    <title>Restoran - Bootstrap Restaurant Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    
    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="https://unpkg.com/htmx.org"></script>

</head>
{% include "admin_templates/navbar.html" %}

<!-- Page Header-->

<!-- Main Content-->

{% block content %}
{% endblock content %}


<!-- Footer-->
{% include "restaurant/footer.html" %}

<!-- JavaScript Libraries -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/easing.min.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/counterup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/moment-timezone.min.js' %}"></script>
<script src="{% static 'js/tempusdominus-bootstrap-4.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

restaurant_app/templates/admin_templates/navbar.html
{%load static%}
  <!-- navbar_other.html -->

  <!-- Navbar & Hero Start -->
  <div class="container-xxl position-relative p-0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
        <a href="" class="navbar-brand p-0">
            <h1 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>Stars Restoran
            </h1>
            <!-- <img src="img/logo.png" alt="Logo"> -->
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="fa fa-bars"></span>
        </button>



        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0 pe-4">
                <a href="{% url 'restaurant_app:home' %}" class="nav-item nav-link {{ home|default:'' }}">Home</a>
                <a href="{% url 'restaurant_app:about' %}" class="nav-item nav-link {{ about|default:'' }}">About</a>
                <a href="{% url 'restaurant_app:services' %}" class="nav-item nav-link {{ service|default:'' }}">Service</a>
                <a href="{% url 'restaurant_app:menu' category='food_menu' %}" class="nav-item nav-link {{ menu|default:'' }}">Menu</a>
                {% comment %} <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu m-0">
                        <a href="booking.html" class="dropdown-item">Booking</a>
                        <a href="team.html" class="dropdown-item">Our Team</a>
                        <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                    </div>
                </div> {% endcomment %}
                <a href="{%url 'restaurant_app:contact'%}" class="nav-item nav-link {{ contact|default:'' }}">Contact</a>
                {% if request.user.is_staff %}
                        <a href="{% url 'restaurant_app:dashboard'%}" class="nav-item nav-link {{ Dashboard|default:'' }}">Admin Dashboard</a>
                        {% endif %}
            </div>
            <a href="{% url 'restaurant_app:cart' %}" class="btn btn-primary py-2 px-4">Orders</a>
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'accounts:logout' %}" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="dropdown-item text-danger d-flex align-items-center">
                    <i class="fas fa-sign-out-alt me-2"></i> Logout
                </button>
            </form>
        {% else %}
            <a href="{% url 'accounts:login' %}" class="btn btn-primary d-flex align-items-center py-1 px-3">
                <i class="fas fa-sign-in-alt me-2"></i> Login
            </a>
        {% endif %}
        
        
        </div>




    </nav>
    <div class="container-xxl py-5 bg-dark hero-header mb-5">
        <div class="container text-center my-5 pt-5 pb-4">
            <!-- Dynamic Page Title -->
            <h1 class="display-3 text-white mb-3 animated slideInDown">{{ page_title }}</h1>
    
        </div>
    </div>
</div>
<!-- Navbar & Hero End -->